### ISSUE TITLE
Music Support?

### ISSUE THREAD

**Issue by BryMD** [andrigamerita/zelda_roth#1]
Hi @andrigamerita :)

Absolutely AWESOME job on your game ports to the MiyooCFW!!

Is there any chance for an updated version of Zelda RotH with music support?

salvacam did a port of Zelda Picross (forked from sauce/gameblabla) that utilized .OGG music and the following Bourne shell script ('conv.sh') in the 'music' folder:

_for i in *.wav ; do 
    ffmpeg -i "$i" -acodec libvorbis "$(basename "${i/.wav}").ogg"
done_

Sincerely,
BryMD

**Comment by andrigamerita** [comment]
Hi @BryMD!
Thank you for trying my ports!

What do you mean by music support? My port already supports music (MIDI, not OGG or WAV)
You can actually see that here: https://www.youtube.com/watch?v=aJYz8uDZhnQ

Both music and sound effects should work (at least on the PocketGo with v1.3.3 CFW, the only Miyoo console I have and thus the only one I test my ports on), check the options of the game, maybe your volume is all the way low (?)

**Comment by BryMD** [comment]
Hi :)

Hehe, then I'm the one in the wrong here :) I'm still on modified 1.3.2 :P

Looking forwards to take your ports for another spin on 1.3.3 once I get around to it!

Keep up the awesome work @andrigamerita !

Sincerely,
BryMD
